name: fwnd
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bitsdojo_window: ^0.1.2
  lottie: ^1.3.0
  
  #Layout
  easy_sidemenu: ^0.3.1
  #FFI


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/animation/drop_water.json
    - assets/windll/sysinfo.dll
